import * as fs from "fs"
import * as path from "path"

// Contract test for the tmc-langs-cli stdout schemas in shared/langsSchema.ts.
//
// The schemas are autogenerated from the vendored JSON Schema artifact
// (shared/bindings.schema.json) via `npm run generate:langs-schema`; this test
// guards against the generated schemas drifting from the real CLI contract.
//
// Two lines of defense:
//  1. Representative CLI output fixtures must (in)validate as expected.
//  2. The generated zod discriminators are cross-checked against the vendored
//     JSON Schema artifact (shared/bindings.schema.json, generated in
//     tmc-langs-rust from the serde types; re-vendor with
//     bin/updateLangsSchema.sh).
import { CliOutput, DataKind } from "../shared/langsSchema"
import { invalidCliOutputFixtures, validCliOutputFixtures } from "./fixtures/cliOutput"

/**
 * Locates the repo-root shared/bindings.schema.json regardless of where the
 * compiled test runs from (out/, dist/testBundle, ...).
 */
function readVendoredSchema(): {
  oneOf: { properties: { "output-kind": { const: string } } }[]
  $defs: Record<
    string,
    {
      oneOf?: { properties?: Record<string, { const?: string }> }[]
      properties?: Record<string, unknown>
    }
  >
} {
  let dir = __dirname
  for (let i = 0; i < 6; i++) {
    const candidate = path.join(dir, "shared", "bindings.schema.json")
    if (fs.existsSync(candidate)) {
      return JSON.parse(fs.readFileSync(candidate, "utf8"))
    }
    dir = path.dirname(dir)
  }
  throw new Error("shared/bindings.schema.json not found")
}

suite("Langs CLI output contract", function () {
  suite("fixtures", function () {
    for (const fixture of validCliOutputFixtures) {
      test(`accepts ${fixture.name}`, function () {
        const result = CliOutput.safeParse(fixture.value)
        expect(
          result.success,
          result.success ? undefined : `expected fixture to validate:\n${result.error.message}`,
        ).toBe(true)
      })
    }

    for (const fixture of invalidCliOutputFixtures) {
      test(`rejects ${fixture.name}`, function () {
        const result = CliOutput.safeParse(fixture.value)
        expect(result.success, "expected fixture to be rejected").toBe(false)
      })
    }
  })

  suite("vendored JSON Schema cross-check", function () {
    test("DataKind covers exactly the output-data-kinds of the vendored schema", function () {
      const schema = readVendoredSchema()
      const schemaKinds = (schema.$defs.DataKind?.oneOf ?? [])
        .map((variant) => variant.properties?.["output-data-kind"]?.const)
        .filter((kind): kind is string => typeof kind === "string")
        .toSorted()
      const zodKinds = DataKind.options
        .map((option) => option.shape["output-data-kind"].value)
        .toSorted()
      expect(schemaKinds.length).toBeGreaterThan(0)
      expect(zodKinds).toEqual(schemaKinds)
    })

    test("CliOutput covers exactly the output-kinds of the vendored schema", function () {
      const schema = readVendoredSchema()
      const schemaKinds = schema.oneOf
        .map((variant) => variant.properties["output-kind"].const)
        .toSorted()
      // extracted manually: the status-update branch is a nested union
      const zodKinds = ["notification", "output-data", "status-update"]
      expect(schemaKinds).toEqual(zodKinds)
      for (const kind of schemaKinds) {
        const minimal = { "output-kind": kind }
        // a bare tag should at least fail on the *body*, not on an
        // unrecognized discriminator: sanity-check that each tag is known
        const result = CliOutput.safeParse(minimal)
        expect(result.success).toBe(false)
      }
    })

    test("CourseDetails is flattened in the vendored schema (serialize contract)", function () {
      // The vendored schema is generated with schemars' serialize
      // contract, so CourseDetails is flat (course fields + unlockables +
      // exercises) exactly as the CLI writes it -- not wrapped in a
      // `{ course: ... }` object (the deserialize shape from
      // #[serde(from = ...)]). If this regresses, the generator switched
      // back to the deserialize contract; re-check output.rs upstream.
      const schema = readVendoredSchema()
      const courseDetails = schema.$defs.CourseDetails
      expect(courseDetails, "CourseDetails must be present in the schema").toBeDefined()
      expect(courseDetails?.properties).not.toHaveProperty("course")
      expect(courseDetails?.properties).toHaveProperty("exercises")
      expect(courseDetails?.properties).toHaveProperty("unlockables")
    })
  })
})
