// The single registration point for the `vscode-*` custom elements, shared by the app and the
// component tests so tests render the same upgraded elements users get.
import "@vscode-elements/elements/dist/vscode-badge/index.js"
import "@vscode-elements/elements/dist/vscode-button/index.js"
import "@vscode-elements/elements/dist/vscode-button-group/index.js"
import "@vscode-elements/elements/dist/vscode-checkbox/index.js"
import "@vscode-elements/elements/dist/vscode-collapsible/index.js"
import "@vscode-elements/elements/dist/vscode-icon/index.js"
import "@vscode-elements/elements/dist/vscode-progress-bar/index.js"
import "@vscode-elements/elements/dist/vscode-progress-ring/index.js"
import "@vscode-elements/elements/dist/vscode-radio/index.js"
import "@vscode-elements/elements/dist/vscode-radio-group/index.js"
import "@vscode-elements/elements/dist/vscode-table/index.js"
import "@vscode-elements/elements/dist/vscode-table-body/index.js"
import "@vscode-elements/elements/dist/vscode-table-cell/index.js"
import "@vscode-elements/elements/dist/vscode-table-header/index.js"
import "@vscode-elements/elements/dist/vscode-table-header-cell/index.js"
import "@vscode-elements/elements/dist/vscode-table-row/index.js"
import "@vscode-elements/elements/dist/vscode-textarea/index.js"
import "@vscode-elements/elements/dist/vscode-toolbar-button/index.js"
